name: Deploy Mini Heroku

on:
  push:
    branches:
      - main
      - dev/**
      - feat/**
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25.6"

      - name: Test Controller
        working-directory: controller
        run: go test -v ./...

      - name: Test CLI
        working-directory: cli
        run: go test -v ./...

  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    needs: test # Only run if tests pass

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25.6"
          cache: true
          cache-dependency-path: |
            controller/go.sum
            cli/go.sum

      - name: Build Controller
        working-directory: controller
        run: GOOS=linux GOARCH=amd64 go build -o controller-linux -v

      - name: Upload Controller Artifact
        uses: actions/upload-artifact@v4
        with:
          name: controller-binary
          path: controller/controller-linux
          retention-days: 1

  deploy:
    name: Deploy to VM
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Controller Artifact
        uses: actions/download-artifact@v4
        with:
          name: controller-binary

      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_IP}}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "SSH Connection successfull"
            whoami
            pwd
            docker --version
